# **Part 5**


**Please install nycflight dataframe package in your Anaconda environment (you can do it on “local” or “discovery”):**

* pip install nycflights13

* from nycflights13 import flights 
- Remove the samples with “NaN” in the feature “dep_delay” in this dataframe. (5 pts)

* Start a Dask Client and set “n_workers=4” for this client.                (5 pts)

* Using dask dataframe to compute the mean and standard deviation for departure delay “dep_delay” of all flights.     (5 pts)

You are required to take a screenshot of Dask Dashboard for running the step 3 with the 3 observed processes “Dask Process”, “Dask Graph”, “Dask Task Stream” in a same JupyterLab window, or use static Dask performance report.
(Hint: since the dataset is small, the execution would be very fast. You may need to take a very quick screen capture.)  
(10 pts)

Note: finish the part 5 in a Jupyter file. Submit this Jupyter file and the screenshot image in the step 4**

In [3]:
# Installing nycflight13
!pip install nycflights13

Requirement already satisfied: nycflights13 in c:\users\nikit\anaconda3\lib\site-packages (0.0.3)
Requirement already satisfied: pandas>=0.24.0 in c:\users\nikit\anaconda3\lib\site-packages (from nycflights13) (1.3.4)
Requirement already satisfied: pytz>=2017.3 in c:\users\nikit\anaconda3\lib\site-packages (from pandas>=0.24.0->nycflights13) (2021.3)
Requirement already satisfied: numpy>=1.17.3 in c:\users\nikit\anaconda3\lib\site-packages (from pandas>=0.24.0->nycflights13) (1.20.3)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\nikit\anaconda3\lib\site-packages (from pandas>=0.24.0->nycflights13) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\nikit\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas>=0.24.0->nycflights13) (1.16.0)

In [4]:
from dask.distributed import Client
client = Client(n_workers=4)
client

C:\Users\nikit\anaconda3\lib\site-packages\distributed\node.py:160: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 61445 instead
  warnings.warn(

In [5]:
import dask                                                    # importing dask library
import dask.dataframe as dd
from nycflights13 import flights                               #from nycflights13 import flights
df = dd.from_pandas(flights, npartitions=4)                    #starting a Dask Client and set “n_workers=4” for this client.
df.head()

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01T10:00:00Z
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01T10:00:00Z
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01T10:00:00Z
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01T10:00:00Z
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01T11:00:00Z

In [6]:
print("Before cleaning the Nan values from the dataframe: {}".format(flights['dep_delay'].isnull().sum()))

Before cleaning the Nan values from the dataframe: 8255

In [7]:
# Removing the samples with null values in the feature “dep_delay” in this dataframe
flights.dropna(subset=['dep_delay'], how ='all', inplace = True)

In [8]:
print("After cleaning the NaN Values from the dataframe: {}".format(flights['dep_delay'].isnull().sum()))

After cleaning the NaN Values from the dataframe: 0

Interpretation: This shows that the dataframe is clean and all the null values are being removed

In [9]:
print(flights.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 328521 entries, 0 to 336769
Data columns (total 19 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   year            328521 non-null  int64
 1   month           328521 non-null  int64
 2   day             328521 non-null  int64
 3   dep_time        328521 non-null  float64
 4   sched_dep_time  328521 non-null  int64
 5   dep_delay       328521 non-null  float64
 6   arr_time        328063 non-null  float64
 7   sched_arr_time  328521 non-null  int64
 8   arr_delay       327346 non-null  float64
 9   carrier         328521 non-null  object
 10  flight          328521 non-null  int64
 11  tailnum         328521 non-null  object
 12  origin          328521 non-null  object
 13  dest            328521 non-null  object
 14  air_time        327346 non-null  float64
 15  distance        328521 non-null  int64
 16  hour            328521 non-null  int64
 17  minute          328521 non-null  int64
 18  time_hour       328521 non-null  object
dtypes: float64(5), int64(9), object(5)
memory usage: 50.1+ MB
None

In [10]:
# Using dask dataframe to compute the mean for departure delay “dep_delay” of all flights
dep_delay_mean = df['dep_delay'].mean().compute()
dep_delay_mean

12.639070257304708

In [11]:
#Using dask dataframe to compute the standard deviation for departure delay “dep_delay” of all flights
dep_delay_std = df['dep_delay'].std().compute()
dep_delay_std

40.21006089212995